name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install truffle
        run: npm install truffle -g

      - name: Build
        run: truffle compile

      - name: Test
        run: truffle test